travis:
  secure:
    BINSTAR_TOKEN: m8W6ZwF+eELX8G5nrwYHAnPF55mFOw0SbM2hK/RWiSzJPIeea7Qu2AiEn9QyNb0PF0PxKYzmkjiywFD9OmXvE67rvq1kjzFMZltrHBcDvCt92keCcpUpih7XhIQ3Pbo2MQW92Na0r7ATWGobE8kxR97VhmoLDJ7nB2LIr5nN1mQFTCrX3lXJxATIOWGk/Rz0pOjHDoU1jLDiCWzJd6W9RMEaJpfvzzGG63APREt+PmVGPorb4fPoglP57Iv9QK2u79qHSwtiaLc5iBUnn+ZgoD+mwoQ10WemfQ8ygYhSREHxWDpPZ8zqB2WRMI3x7c9sngnqQOHdOBSyIbIdVhuRgk1gTve9E+Uz+YZqtIVjmZercg8Hdjc8kHeew3IJ2XcFUW4Yc1VVZ/uM9gp8h1zAY634U6GvwIZfql9bfhyqlZkoT8mQsNKc2SvQ4/wRx/Mo9LQl/ui8U7OBVd4vrx2TkeuKCoo0jDkpihbuFTiTtiMA+80m8jmXQDnUvuGEqa7YFyDdYZ+p/yTvejoKwhorBwtVbU4q2rgN5yiLUiMbTybaBm+2F3iaH+P+i4Bb0Aetcc2+PUnKWjcTeXirztywYmrvSsfIorolABfeNaRBe15KMIkae25x+p4AFFhVAe368d5Z7LlpLCAzAMAVE40fVoKoZ8UEq+Jm0mKwgUNCeG4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
