appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: O/XoUu7eccM2xEzkJEZr1i636Gk9Rg8Z2rWaoX1cpTKeuA1v97NiygbwKTokV82mnkqOYxQ/kCG7I5wQdiT4p9HoIOL04xZupuQzF1uqMDalVinip+78jsKeHK/7dUdENEuOLLKgY6tZucUub6M+1aTGOO8++TxvwIEXCrBCoqi+zHN3a0EyH2QH2UDCwh16yaDUVIw5ZUQZF6qeHiGm4iRscgt1Hpu0LVq0R3TD8eCt7/E0uU9W6XdE/g7Gqgdo9UEHVNE1SGHSByGvwihc7v0G15t+/bVRr9v5l5Y67dc0StmB2f1v9q6TodhcbFXLbzTTBETaxchuBMJMeJPLnPxQZxQ3q3CilMbIQzo0BrfPtOtLxJBa9XzJMyCpZqwrYSHM3MkTA/HhU3BuLomwMPyIrJJ83BzxIUDMG/Fn0ibWCvAUx3kZfA2D9XyxQ9da5WBN8NXrLWj8EM6jIdtQIuvVeLSpvJpNlEcKdDRQVogL1W0FG6EbNRGq7lmQro3sxBAlKwMVePgtjH2Mvic7gTtlV3+D+voFT59n10sajX/etJQzhZpGsqxoFDm11O7x0hfXHjzaGIlHV5mxkdpm2J65WJxQwYDBIktBGutE+S9SUaEIlmW7zNZh7L9sF4w55v01pMJNmjkPeBihDGqN8D3spDD6aHHS2IrRrqcfqTE=
conda_forge_output_validation: true
